### ISSUE TITLE
%mvn_build --xmvn-debug does not work with Maven 3.4.0

### ISSUE THREAD

**Issue by mizdebsk** [fedora-java/javapackages#1]
`--xmvn-debug` option of `%mvn_build` enables XMvn debug output by configuring `slf4j-simple` logging sink - it sets `org.slf4j.simpleLogger.log.org.fedoraproject.xmvn` property to `debug`. Since Maven 3.4.0, a [different logging backend](https://github.com/jdillon/gossip) is used, which doesn't recognize this property.

**Comment by mizdebsk** [comment]
XMvn introduced property "xmvn.debug", which can be used to enable debug output for all supported logger sinks.

**Comment by rvais** [comment]
Replace old debug system property for new one
