### ISSUE TITLE
Dependency on java-11-openjdk-headless (which will be EOL in a week) on RHEL9 

### ISSUE THREAD

**Issue by nikosmoum** [fedora-java/javapackages#134]
Hi,

We have been using javapackages-tools as a dependency, and were just made aware that it is dependent on java-11-openjdk-headless, specifically on RHEL9. This is a problem since Java 11 is becoming EOL for RHEL at the end of this month.  Is there a chance you can get an update out by then, or should we be looking to find a workaround?

Thanks,
Nikos

**Comment by mizdebsk** [comment]
Javapackages project does not have and never had dependency on any particular version of Java.

There used to be a "default JDK/JRE" settings, which were configurable. RHEL 9 configured them to OpenJDK 11. There is a RHEL issue about this problem: https://issues.redhat.com/browse/RHEL-62177. You can use that Jira issue or contact Red Hat support at https://access.redhat.com/support/

Moreover, the notion of "default JDK/JRE" was recently removed in 459237d7b12544632a632eb9b3189004b7548c49.

Anyway, this is not an issue in the upstream javapackages project, so I'm closing this issue.
