### ISSUE TITLE
Remove references Fedora-Review plugin

### ISSUE THREAD

**Issue by mizdebsk** [fedora-java/javapackages#17]
Fedora-Review plugin has been extracted as a separate project. Lets get rid of any remaining references to it.

**Comment by msimacek** [comment]
Where do you see any?

**Comment by mizdebsk** [comment]
> Where do you see any?

https://github.com/fedora-java/javapackages/blob/master/aux/javapackages-tools.spec#L133

**Comment by msimacek** [comment]
Anything else?

**Comment by mizdebsk** [comment]
> Anything else?

No, it looks like that's the only reference.
