### ISSUE TITLE
Deprecate %add_maven_depmap

### ISSUE THREAD

**Issue by mizdebsk** [fedora-java/javapackages#20]
Some macros should be deprecated:
- %ant - these days ant has a working launcher which doesn't require setting JAVA_HOME
- %jpackage_script - will replaced with Java launcher macro (https://github.com/fedora-java/javapackages/issues/9)
- %add_maven_depmap - obsoleted by %mvn_artifact

Deprecated macros should be clearly marked as such in comments and documentation. A warning printed when such macro is used would be extra useful - we could reach people not reading docs and grep build logs to find packages using these macros.

**Comment by msimacek** [comment]
> %ant - these days ant has a working launcher which doesn't require setting JAVA_HOME

I don't agree with this one. Deprecating is necessary for things like `%add_maven_depmap` which create a lot of maintenance burden for us. But `%ant` doesn't, it's a single line macro with no code. If JAVA_HOME is not needed, then I'd rather change it to just expand to `ant`. Deprecating and subsequently removing it would inflict additional work on packagers for virtually no reason.

> %jpackage_script - will replaced with Java launcher macro (#9)

Should be deprecated, but after the replacement is made and released. Not immediately.

> %add_maven_depmap - obsoleted by %mvn_artifact

Agreed, it should have been deprecated already.

**Comment by mizdebsk** [comment]
After rethinking this I agree with @msimacek regarding `%ant` - it can be left unchanged.

Regarding `%jpackage_script` deprecation, please note that this change is scheduled for 5.0.0 release, which won't happen before Java 9. We don't need to merge this PR before Java launcher is implemented.

**Comment by msimacek** [comment]
Java launcher won't make it for 5.0.0, but I think we should still deprecate `%add_maven_depmap` in 5.0.0. I'll change this issue to just that and pick the `%add_maven_depmap` change from the PR
