### ISSUE TITLE
Versioned OSGi auto-requires don't work

### ISSUE THREAD

**Issue by mizdebsk** [fedora-java/javapackages#26]
Versioned OSGi auto-requires don't work at all.

Example:
- hamcrest and hamcrest-core are both built from the same source package - hamcrest.
- hamcrest-core provides `osgi(org.hamcrest.core) = 1.3.0`
- hamcrest requires `osgi(org.hamcrest.core)`, but it should be `osgi(org.hamcrest.core) = 1.3.0`

Versioned OSGi requires would allow dropping manual versioned requires without fear of getting another, incompatible bundle provider installed (like hamcrest12 compat package).

@mbooth101 Please correct me if that's not what we want.

**Comment by mbooth101** [comment]
> Please correct me if that's not what we want.

Sounds exactly like what we want, thanks :-)

**Comment by mizdebsk** [comment]
Fix was [backported](http://pkgs.fedoraproject.org/cgit/rpms/javapackages-tools.git/commit/?id=c5c252bdb3ef9f1eb0449b528e8bb84d25567c79) to Fedora rawhide.
