### ISSUE TITLE
Merge eclipse-filesystem

### ISSUE THREAD

**Issue by mizdebsk** [fedora-java/javapackages#34]
Lets make javapackages own Eclipse-related directories and provide eclipse.conf.
It should be easier to maintain this way.

CC @mbooth101

**Comment by mizdebsk** [comment]
I totally forgot that eclipse-filesystem is archful package, so this is not as easy as it seemed.

**Comment by mizdebsk** [comment]
It looks like in near future Eclipse may be moving to noarch directory layout (/usr/lib will be used for all), so I'm reopening this.

**Comment by mbooth101** [comment]
This is cool, @mizdebsk please feel free to ping me about retiring the eclipse-filesystem package when this makes it into fedora

**Comment by mizdebsk** [comment]
@mbooth101 Sure. For now this is merged into master branch only (which will be next major upstream version). Not sure when this will make into Fedora - probably F28 or later.
