### ISSUE TITLE
--without tests | --without javadoc should get documented

### ISSUE THREAD

**Issue by jerboaa** [fedora-java/javapackages#62]
Any spec file using `%mvn_build` macro will get automatic support for `-f` via RPM conditionals by specifying `--without tests` or `--without javadoc` on the mock/fedpkg invocation. This is surprising since it does not show up in any docs.

FWIW, I went down a path of implementing that feature locally to one spec file and noticed that it was producing multiple `-f` switches when being used. Adding this to the [javapackages docs](https://fedora-java.github.io/howto/latest/) should fix this.

**Comment by mizdebsk** [comment]
This will also need to be documented in mvn_build(7) manpage, in ENVIRONMENT section, next to xmvn_bootstrap macro.

**Comment by mizdebsk** [comment]
Fixed in d398d14290e75b013661803f405258b32da01e91
