### ISSUE TITLE
typo: jvm-commmon in macros.javapackages-filesystem

### ISSUE THREAD

**Issue by develop7** [fedora-java/javapackages#68]
Expected `jvm-common` with 2 `m`s.

See https://github.com/fedora-java/javapackages/blob/ec1bd7d28a5926afd2f4ee15f8533c338ca724a3/macros.d/macros.javapackages-filesystem#L41-L51

**Comment by mizdebsk** [comment]
Fixed, thanks!

**Comment by develop7** [comment]
Do you think it is worth a minor/patch release?
