### ISSUE TITLE
Add dependency generators for RHEL 6

### ISSUE THREAD

**Issue by mizdebsk** [fedora-java/javapackages#7]
Last time I checked, dependency generators didn't work with RPM version shipped with RHEL 6 (without wrapper scripts). This should be confirmed and fixed, possibly by adding such wrapper scripts.

**Comment by msimacek** [comment]
> Last time I checked, dependency generators didn't with RPM version shipped with RHEL 6

I'm missing a verb in the sentence. Didn't what? Didn't work?

**Comment by mizdebsk** [comment]
> I'm missing a verb in the sentence. Didn't what? Didn't work?

Yes, I've fixed the comment.

**Comment by mizdebsk** [comment]
To be more specific, our dependency generators rely on "pluggable file attribute + dependency extraction system" - feature of RPM implemented in March 2010, https://github.com/rpm-software-management/rpm/commit/8c7e53ec80e84f48bfc67181f3d5dd81ecdb7523. RHEL 6 ships with RPM 4.8.0, released in January 2010, which is missing this feature.

**Comment by mizdebsk** [comment]
Not needed any longer.
